trigger:
- main

pool:
  name: Default   # self hosted agent VM name

variables:
  imageName: cloudshieldapp

stages:

- stage: Build
  jobs:
  - job: BuildJob
    steps:

    - checkout: self

    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'
        publishJUnitResults: false

    - script: |
        mvn sonar:sonar \
        -Dsonar.host.url=http://localhost:9000 \
        -Dsonar.login=admin \
        -Dsonar.password=admin
      displayName: SonarQube Scan

    - script: |
        docker build -t $(imageName):$(Build.BuildId) .
      displayName: Docker Build

    - script: |
        trivy image $(imageName):$(Build.BuildId)
      displayName: Trivy Scan

    - task: Docker@2
      inputs:
        containerRegistry: 'acr-connection'
        repository: 'cloudshieldapp'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)